version: "3.3"
services:
  xsshunterexpress:
    build: .
    environment:
      - HOSTNAME=xsshunter6179.onrender.com
      - SSL_CONTACT_EMAIL=khrishop007@gmail.com
      - MAX_PAYLOAD_UPLOAD_SIZE_MB=50
      - CONTROL_PANEL_ENABLED=true
      - SMTP_EMAIL_NOTIFICATIONS_ENABLED=false
      - SCREENSHOTS_DIR=/app/payload-fire-images
      - DATABASE_NAME=xsshunter_db
      - DATABASE_USER=xsshunter_db_user
      - DATABASE_PASSWORD=LjfsTfgaQY24QG3olRlmouRDNETvz0ff
      - DATABASE_HOST=dpg-d74hvr2dbo4c738tabo0-a
      - NODE_ENV=production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssldata:/app/greenlock.d
      - ./payload-fire-images:/app/payload-fire-images
